# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

#-------------------------------------------------------------->


trigger:
- master

pool:
  name: Default  # Using the Default agent pool
  demands:
  - agent.name -equals AsocVM2  # Specify the self-hosted agent by its name

variables:
  - group: "ASOC"

stages:
  - stage: OX_Security_Scan
    displayName: OX Security Scan
    jobs:
      - job: OX
        displayName: Run OX Security Scan
        steps:
          - script: |
              curl -i -k https://app.asoc-dev.bosch.com
              curl -i -k https://api.asoc-dev.bosch.com
              docker run \
              -e OX_HOST_URL=$(ASOC_HOST1) \
              -e OX_API_KEY=$(ASOC_API_KEY) \
              -e OX_DISABLE_SSL_VALIDATION=true \
              --env-file <(env | grep 'SYSTEM_\|BUILD_') \
              oxsecurity/ox-block-mode:latest
            displayName: Execute OX Security Scan
